### PR TITLE
Fix Disqus Comments

### PR DESCRIPTION
**Pull request by ayushjain01**
There were a few CSP issues with the old files. To avoid any dependency issues I have created a separate dedicated file with the Disqus embed code, and deleted other comment provider embed codes.
Comments seem to be working smoothly now.

### CODE REVIEW

**Comment by ayushjain01** [comment]
Contribute button is now on right side with every article, and SEO front matter details are also added to "how to contribute" page.

**Comment by ayushjain01** [comment]
Duplicate SEO tags fixed, working on keywords and author tag

**Comment by ayushjain01** [comment]
Fixed SEO author tag and added guildelines as well to add a custom author

**Comment by ayushjain01** [comment]
Removed the default meta description tag and added a custom tag for keywords.
jekyll-seo-tag by default does not add a meta keywords tag since Google often disregards it, so I have added a custom command to add the keywords tag.

**Review by tankala — APPROVED** [review]

**Pull request merged**
